from __future__ import annotations

import ast
from pathlib import Path
import shutil


BASE_DIR = Path(__file__).resolve().parent
SOURCE_DATASET = BASE_DIR / "FOOD-INGREDIENTS dataset.v2i.yolov11"
TARGET_DATASET = BASE_DIR / "FOOD-INGREDIENTS dataset.v2i.yolov11_na_merged"


def read_names(data_yaml: Path) -> list[str]:
    for line in data_yaml.read_text().splitlines():
        if line.startswith("names:"):
            return ast.literal_eval(line.split("names:", 1)[1].strip())
    raise ValueError("Could not find names in data.yaml")


def rewrite_label_file(src: Path, dst: Path, mapping: dict[int, int]) -> None:
    out_lines: list[str] = []
    for raw in src.read_text().splitlines():
        line = raw.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 5:
            continue
        old_id = int(parts[0])
        parts[0] = str(mapping[old_id])
        out_lines.append(" ".join(parts))
    dst.write_text("\n".join(out_lines) + ("\n" if out_lines else ""))


def main() -> None:
    names = read_names(SOURCE_DATASET / "data.yaml")

    # Merge all "NA" classes into a single class ID.
    new_names: list[str] = []
    old_to_new: dict[int, int] = {}
    na_new_id: int | None = None

    for old_id, name in enumerate(names):
        if name == "NA":
            if na_new_id is None:
                na_new_id = len(new_names)
                new_names.append("NA")
            old_to_new[old_id] = na_new_id
        else:
            old_to_new[old_id] = len(new_names)
            new_names.append(name)

    if TARGET_DATASET.exists():
        shutil.rmtree(TARGET_DATASET)
    TARGET_DATASET.mkdir(parents=True, exist_ok=True)

    for split in ("train", "valid", "test"):
        src_images = SOURCE_DATASET / split / "images"
        src_labels = SOURCE_DATASET / split / "labels"
        dst_images = TARGET_DATASET / split / "images"
        dst_labels = TARGET_DATASET / split / "labels"
        dst_images.mkdir(parents=True, exist_ok=True)
        dst_labels.mkdir(parents=True, exist_ok=True)

        for image_file in src_images.iterdir():
            (dst_images / image_file.name).symlink_to(image_file.resolve())
        for label_file in src_labels.iterdir():
            rewrite_label_file(label_file, dst_labels / label_file.name, old_to_new)

    (TARGET_DATASET / "data.yaml").write_text(
        "\n".join(
            [
                "train: ../train/images",
                "val: ../valid/images",
                "test: ../test/images",
                "",
                f"nc: {len(new_names)}",
                f"names: {new_names}",
                "",
                "# Generated by merge_na_class.py",
            ]
        )
        + "\n"
    )

    print(f"Original classes: {len(names)}")
    print(f"New classes: {len(new_names)}")
    print(f"NA class count in new names: {sum(1 for n in new_names if n == 'NA')}")
    print(f"Wrote: {TARGET_DATASET}")


if __name__ == "__main__":
    main()
